apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector: 
    app: webserver-multiport
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8090
