apiVersion: v1
kind: ReplicationController
metadata:
  name: rccontroller-nginx
spec:
  replicas: 3
  selector:
    app: my-nginx-app
  template:
    metadata:
      name: nginx-pod
      labels:
        app: my-nginx-app
    spec:
      containers:
        - name: nginx-container
          image: coolgourav147/nginx-custom
