apiVersion: v1
kind: LimitRange
metadata:
  name: testlimit
spec:
  limits:
    - default:
        cpu: 200m
        memory: 500Mi
      defaultRequest:
        cpu: 100m
        memory: 250Mi
      type: Container
