apiVersion: v1
kind: Pod
metadata:
  name: hostpathvolumepod
spec:
  containers:
    - name: test-container
      image: coolgourav147/nginx-custom
      volumeMounts:
        - mountPath: /data
          name: first-volume
  volumes:
    - name: first-volume
      hostPath:
        path: /tmp/data
