# kubeadm-config.yaml
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
networking:
  podSubnet: "10.244.0.0/16" # --pod-network-cidr
kubernetesVersion: v1.21.0
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
networking:
  podSubnet: "10.244.0.0/16" # --pod-network-cidr
cgroupDriver: systemd
