apiVersion: v1
kind: Pod
metadata:
  name: podrequestingresources
spec:
  containers:
    - image: nginx:latest
      name: firstcontainer
      resources:
        requests:
          cpu: 0.5
          memory: 250Mi
        limits:
          cpu: 1
          memory: 500Mi
