apiVersion: v1
kind: Pod
metadata:
  name: testwebserver
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: coolgourav147/nginx-custom
      resources:
        requests:
          memory: 100Mi
        limits:
          memory: 1000Mi
    

