apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    env: prod
spec:
  containers:
    - name: myfirstcontainer
      image: coolgourav147/nginx-custom
      env:
        - name: myname
          value: "fahad"
        - name: age
          value: "33"
        - name: city
          value: "karachi"
    - name: secondcontainer
      image: coolgourav147/nginx-custom


