apiVersion: v1
kind: Pod
metadata:
  name: injectsecretmulitpleval
spec:
  containers:
    - image: nginx:latest
      name: firstcontainers
      envFrom:
        - secretRef:
            name: fromenvfile
