apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdeploy
  labels:
    name: firstdeploy
  annotations:
    kubernetes.io/change-cause: "my custom message"
spec:
  replicas: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: dpod
      labels:
        app: myapp
    spec:
      containers:
        - image: coolgourav147/nginx-custom
          name: container
