apiVersion: v1
kind: Pod
metadata:
  name: injectsecret
spec:
  containers:
    - image: nginx:latest
      name: firstcontainers
      env:
        - name: myvariable
          valueFrom:
            secretKeyRef:
              key: variable1
              name: fromenvfile
