apiVersion: v1
kind: Pod
metadata:
  name: secretfromfile
spec:
  containers:
    - name: myfirstcontainer
      image: nginx:latest
      volumeMounts:
        - mountPath: /secrets
          name: volumename
  volumes:
    - name: volumename
      secret:
        secretName: fromenvfile
