apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    label1: fahad
    label2: meraj
spec:
  containers:
    - name: firstcontainer
      image: coolgourav147/nginx-custom
      env:
        - name: name
          value: "fahad"
        - name: age
          value: "33"
  initContainers:
    - name: initcontainer
      image: coolgourav147/nginx-custom
      args: ["sleep","30"]
